apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        env: development
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3

