apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replica
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: nginx-3
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx-3
        image: nginx
